"""add companies and recruiter company relationship

Revision ID: 86847c4ad53a
Revises: 686f5e817bad
Create Date: 2026-08-30 20:28:34.707142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86847c4ad53a'
down_revision: Union[str, Sequence[str], None] = '686f5e817bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recruiters', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_recruiters_company_id'), 'recruiters', ['company_id'], unique=False)
    op.create_foreign_key('fk_recruiters_company_id', 'recruiters', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recruiters_company_id', 'recruiters', type_='foreignkey')
    op.drop_index(op.f('ix_recruiters_company_id'), table_name='recruiters')
    op.drop_column('recruiters', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
